# Generated by Django 4.0.3 on 2022-03-10 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sale_Person', models.TextField()),
                ('Customer_Name', models.TextField()),
                ('Customer_Country', models.TextField()),
                ('Desired_Fruit', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
