# Generated by Django 4.0.3 on 2022-03-10 22:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='date',
            field=models.DateField(default=datetime.date(2022, 3, 10)),
        ),
    ]
