# Generated by Django 4.0.3 on 2022-03-10 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleapp', '0002_alter_sales_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='Sale_Person',
            field=models.CharField(choices=[('anna', 'Green'), ('bob', 'Blue')], default='Select', max_length=6),
        ),
    ]
