# Generated by Django 4.0.3 on 2022-03-10 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleapp', '0003_alter_sales_sale_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='Sale_Person',
            field=models.CharField(choices=[('Anna', 'Anna'), ('Bob', 'Bob'), ('Charlene', 'Charlene'), ('David', 'David')], default='Select', max_length=10),
        ),
    ]
