# Generated by Django 4.0.3 on 2022-03-10 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleapp', '0005_alter_sales_customer_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales',
            old_name='date',
            new_name='Date',
        ),
        migrations.AlterField(
            model_name='sales',
            name='Desired_Fruit',
            field=models.CharField(choices=[('Apple', 'Apple'), ('Pears', 'Pears'), ('Strawberries', 'Strawberries'), ('Banana', 'Banana')], default='Select', max_length=12),
        ),
    ]
