# Generated by Django 4.0.3 on 2022-03-11 12:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleapp', '0006_rename_date_sales_date_alter_sales_desired_fruit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='Customer_Name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='sales',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 3, 11)),
        ),
    ]
