# Generated by Django 4.0.3 on 2022-03-11 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleapp', '0008_remove_sales_desired_fruit'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='Desired_Fruit',
            field=models.CharField(choices=[('Apple', 'Apple'), ('Pears', 'Pears'), ('Strawberries', 'Strawberries'), ('Banana', 'Banana')], default='Select', max_length=12),
        ),
    ]
