# Generated by Django 4.0.3 on 2022-03-12 11:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleapp', '0010_fruits_remove_sales_desired_fruit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fruits',
            old_name='Desired_Fruit',
            new_name='fruit_name',
        ),
        migrations.AlterField(
            model_name='sales',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 3, 12)),
        ),
    ]
