# Generated by Django 4.0.3 on 2022-03-12 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleapp', '0011_rename_desired_fruit_fruits_fruit_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='Customer_Country',
            field=models.CharField(blank=True, choices=[('UK', 'UK'), ('France', 'France'), ('Germany', 'Germany'), ('Netherlands', 'Netherlands'), ('Spain', 'Spain')], default='Select', max_length=12),
        ),
        migrations.AlterField(
            model_name='sales',
            name='Sale_Person',
            field=models.CharField(blank=True, choices=[('Anna', 'Anna'), ('Bob', 'Bob'), ('Charlene', 'Charlene'), ('David', 'David')], default='Select', max_length=10),
        ),
    ]
