# Generated by Django 4.0.3 on 2022-03-12 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleapp', '0012_alter_sales_customer_country_alter_sales_sale_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='Customer_Country',
            field=models.CharField(choices=[('UK', 'UK'), ('France', 'France'), ('Germany', 'Germany'), ('Netherlands', 'Netherlands'), ('Spain', 'Spain')], default='Select', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='Customer_Name',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='Date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='Sale_Person',
            field=models.CharField(choices=[('Anna', 'Anna'), ('Bob', 'Bob'), ('Charlene', 'Charlene'), ('David', 'David')], default='Select', max_length=10, null=True),
        ),
    ]
